const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const titles={overview:'营销总览',opportunities:'机会工作台',audiences:'客群工作台',products:'产品包工作台',contents:'内容工作台',campaigns:'营销活动中心',approvals:'审批中心',execution:'执行监控',feedback:'效果复盘',graph:'知识中心',permissions:'权限与审计'};
let toastTimer=null,wizardStep=0,selectedDecision='approve',editingCampaignRow=null;const toastEl=$('#toast');
function toast(t){if(!toastEl)return;toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),2800)}
function icons(){if(window.lucide)lucide.createIcons()}
function activate(view){$$('.nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));if($('#crumbTitle'))$('#crumbTitle').textContent=titles[view]||titles.overview;if($('#activeTab'))$('#activeTab').textContent=titles[view]||titles.overview;if(view==='graph')requestAnimationFrame(()=>{if(window.graph&&typeof window.graph.resize==='function')window.graph.resize();})}
document.addEventListener('click',event=>{
  const toggle=event.target.closest('.menu-toggle');
  if(toggle){
    event.preventDefault();
    event.stopPropagation();
    const group=toggle.closest('.menu-group');
    const expanded=!group.classList.contains('open');
    group.classList.toggle('open',expanded);
    toggle.setAttribute('aria-expanded',String(expanded));
    return;
  }
  const nav=event.target.closest('.nav button[data-view]');
  if(nav)activate(nav.dataset.view);
});
$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>activate(b.dataset.jump)));
function openLayer(id){const e=$(`#${id}`);if(e){e.classList.add('open');e.setAttribute('aria-hidden','false');document.body.classList.add('layer-open');icons()}}function closeLayer(id){const e=$(`#${id}`);if(e){e.classList.remove('open');e.setAttribute('aria-hidden','true')}if(!$('.modal-layer.open,.drawer-layer.open'))document.body.classList.remove('layer-open')}
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeLayer(b.dataset.close)));
function setStep(n){wizardStep=Math.max(0,Math.min(3,n));$$('.wizard-page').forEach(p=>p.classList.toggle('active',+p.dataset.step===wizardStep));$$('.wizard-steps span').forEach((s,i)=>{s.classList.toggle('active',i===wizardStep);s.classList.toggle('done',i<wizardStep)});if($('#wizardPrev'))$('#wizardPrev').style.visibility=wizardStep?'visible':'hidden';if($('#wizardNext'))$('#wizardNext').textContent=wizardStep===3?'提交审批':'下一步';if($('#wizardSubtitle'))$('#wizardSubtitle').textContent=`步骤${wizardStep+1}/4 · ${['基本信息','客群与产品','内容与触达','检查并提交'][wizardStep]}`}
function openCampaign(name=''){openLayer('campaignModal');setStep(0);if($('#campaignName'))$('#campaignName').value=name;icons()}
function campaignActionCell(){return '<td class="campaign-actions"><button class="btn" data-campaign-action="view">查看</button><button class="btn" data-campaign-action="edit">编辑</button><button class="btn danger" data-campaign-action="delete">删除</button></td>'}
function bindCampaignRows(){ $$('#campaigns .table tr').forEach(tr=>{if(!/^ACT-/.test(tr.cells?.[0]?.textContent?.trim()||''))return;const action=tr.querySelector('.action');if(action)action.outerHTML=campaignActionCell()})}
function addCampaign(name){const tables=$$('#campaigns .table');const table=tables[0];if(!table)return;const tr=table.insertRow(1);tr.innerHTML=`<td>ACT-2026-${String(922+tables[0].rows.length).padStart(4,'0')}</td><td><strong>${name}</strong></td><td>草稿</td><td>V1 · 草案</td><td>张琳</td><td>刚刚</td><td><span class="status warn">待提交</span></td>${campaignActionCell()}`}
async function submitCampaign(){const name=$('#campaignName')?.value?.trim()||'未命名活动';if(editingCampaignRow){const title=editingCampaignRow.querySelector('td:nth-child(2) strong');if(title)title.textContent=name;editingCampaignRow=null;closeLayer('campaignModal');toast(`活动已更新：${name}`);return}if(window.createProductionCampaign){try{const item=await window.createProductionCampaign(name);closeLayer('campaignModal');activate('campaigns');toast(`活动“${item.name}”已创建，编号 ${item.id}`);return}catch(error){toast(error.message||'活动创建失败');return}}addCampaign(name);closeLayer('campaignModal');activate('campaigns');toast(`活动“${name}”已创建，已生成V1草案，等待配置客群、产品和内容`);bindCampaignRows()}
$('#wizardNext')?.addEventListener('click',()=>wizardStep===3?submitCampaign():setStep(wizardStep+1));$('#wizardPrev')?.addEventListener('click',()=>setStep(wizardStep-1));
bindCampaignRows();
$('#campaigns')?.addEventListener('click',e=>{const button=e.target.closest('[data-campaign-action]');if(!button)return;const row=button.closest('tr');const name=row?.querySelector('td:nth-child(2) strong')?.textContent?.trim()||'未命名活动';if(button.dataset.campaignAction==='view'){openCampaign(name);toast(`已打开活动“${name}”`)}if(button.dataset.campaignAction==='edit'){editingCampaignRow=row;openCampaign(name);toast(`已载入活动“${name}”，可修改活动信息`)}if(button.dataset.campaignAction==='delete'){if(!window.confirm(`确认删除活动“${name}”？删除后不可恢复。`))return;row.remove();toast(`活动“${name}”已删除`)}});
$$('.life').forEach(b=>b.addEventListener('click',()=>{activate(b.dataset.jump);toast(`已进入${titles[b.dataset.jump]}，当前活动生命周期节点已定位`)}));
$$('[data-open-campaign]').forEach(b=>b.addEventListener('click',()=>{activate('campaigns');toast(`已打开活动：${b.dataset.openCampaign}`)}));
$$('[data-open-opportunity]').forEach(b=>b.addEventListener('click',()=>{const title=b.dataset.openOpportunity;$('#opportunityDetail').querySelector('h3').textContent=title;toast(`已加载机会详情：${title}`)}));
$$('[data-audience]').forEach(b=>b.addEventListener('click',()=>showAudience(b.dataset.audience)));
function showAudience(type){const data={'high-intent':['三亚高意向未购','36,420','酒店搜索、比价期、未出票、价格敏感'],family:['家庭出游相似客群','18,620','同行人关系、行李需求、暑期出行'],business:['金卡商务两舱潜客','9,840','公务舱偏好、京沪频次、升舱意愿']}[type]||['三亚高意向未购','36,420','酒店搜索、比价期、未出票'];const box=$('#audienceDetail');box.innerHTML=`<div class="detail-block"><h3>${data[0]}</h3><div class="tag-row"><span class="tag blue">动态客群</span><span class="tag green">可触达</span><span class="tag amber">V4</span></div></div><div class="detail-grid"><span>客群人数</span><b>${data[1]}人</b><span>核心画像</span><b>${data[2]}</b><span>旅程阶段</span><b>比价期 · 未出票</b><span>触达许可</span><b>可触达，7天已触达1次</b><span>关联活动</span><b>上海—三亚国庆早鸟</b></div><div class="ai-result"><b>用户洞察智能域</b><p>已完成关系扩展和保护排除，建议匹配早鸟机票、行李和优选座位产品包。</p></div><div class="business-actions"><button class="btn" data-action="exportAudience">导出快照</button><button class="btn primary" data-action="addAudienceCampaign">加入活动</button></div>`;$('#audienceDetailTitle').textContent=data[0];icons()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)action(b.dataset.action,b)});
function action(a,b){
  const routes={newAudience:'audiences',newProduct:'products',newContent:'contents',reviewContent:'contents',viewContent:'contents',viewProduct:'products',viewAudienceSnapshot:'execution',retryFailed:'execution',refreshExecution:'execution',pauseCampaign:'execution',pauseWindow:'execution',exportCampaign:'campaigns',exportReview:'feedback',useOpportunity:'opportunities',useAudience:'audiences',useProduct:'products',useFeedback:'feedback'};
  if(a==='createCampaign'){openCampaign();return;}
  if(routes[a]){activate(routes[a]);toast(a==='refreshExecution'?'\u6267\u884c\u72b6\u6001\u5df2\u5237\u65b0\uff1a\u6e20\u9053\u56de\u6267\u6b63\u5e38':a==='retryFailed'?'\u5931\u8d25\u4efb\u52a1\u5df2\u8fdb\u5165\u91cd\u8bd5\u961f\u5217\uff1a126\u4eba':'\u5df2\u6253\u5f00\u5bf9\u5e94\u4e1a\u52a1\u8be6\u60c5');if(a==='useAudience')showAudience('high-intent');return;}
  if(a==='newAudience'||a==='newProduct'||a==='newContent'){activate(routes[a]);toast('\u5df2\u8fdb\u5165\u521b\u5efa\u5de5\u4f5c\u53f0\uff0c\u53ef\u4fdd\u5b58\u4e3a\u8349\u7a3f');return;}
  if(a==='scanOpportunity'){b.disabled=true;b.textContent='\u626b\u63cf\u4e2d';setTimeout(()=>{b.disabled=false;b.textContent='\u5df2\u53d1\u73b05\u6761';toast('\u673a\u4f1a\u6d1e\u5bdf\u5df2\u5b8c\u6210')},900);return;}
  if(a==='naturalAudience'){activate('audiences');toast('\u81ea\u7136\u8bed\u8a00\u5708\u9009\u5df2\u89e3\u6790');return;}
  if(a==='calculateAudience'){toast('\u5ba2\u7fa4\u8ba1\u7b97\u5b8c\u6210\uff1a36,420\u4eba');return;}
  if(a==='addAudienceCampaign'){openCampaign('\u4e0a\u6d77\u2014\u4e09\u4e9a\u56fd\u5e86\u65e9\u9e1f');setStep(1);toast('\u5ba2\u7fa4\u5df2\u5e26\u5165\u6d3b\u52a8\u8349\u6848');return;}
  if(a==='exportAudience'){toast('\u5ba2\u7fa4\u5feb\u7167\u5bfc\u51fa\u4efb\u52a1\u5df2\u521b\u5efa');return;}
  if(a==='aiOrchestrate'){openCampaign('\u4e0a\u6d77\u2014\u4e09\u4e9a\u56fd\u5e86\u65e9\u9e1f');setStep(1);toast('\u6d3b\u52a8\u7f16\u6392\u5df2\u586b\u5145\u5efa\u8bae');return;}
  if(a==='generateContent'){b.disabled=true;b.textContent='\u751f\u6210\u4e2d';setTimeout(()=>{b.disabled=false;b.textContent='\u5df2\u751f\u62103\u7248';toast('\u5185\u5bb9\u751f\u6210\u5b8c\u6210')},800);return;}
  if(a==='viewVersion'||a==='compareVersion'||a==='rollbackVersion'){toast(a==='viewVersion'?'\u5df2\u6253\u5f00\u7248\u672c\u8be6\u60c5':a==='compareVersion'?'\u5df2\u6253\u5f00\u7248\u672c\u5bf9\u6bd4':'\u5df2\u63d0\u4ea4\u56de\u6eda\u7533\u8bf7');return;}
  if(a==='generateReview'){const box=$('#reviewBox');if(box){box.innerHTML='<div class="ai-result"><b>\u6548\u679c\u5206\u6790\u5df2\u5b8c\u6210</b><p>\u5df2\u751f\u6210\u590d\u76d8\u548c\u4e0b\u4e00\u8f6e\u7b56\u7565\u5efa\u8bae</p></div>';icons();}toast('\u590d\u76d8\u5b8c\u6210');return;}
  if(a==='traceLifecycle'){activate('graph');if(window.graph&&typeof window.graph.highlight==='function')window.graph.highlight();toast('\u5df2\u9ad8\u4eae\u6d3b\u52a8\u5168\u94fe\u8def');return;}
  toast('\u64cd\u4f5c\u5df2\u53d7\u7406');
}
document.addEventListener('click',event=>{
  const button=event.target.closest('button'); if(!button)return;
  if(button.id==='wizardNext'){event.preventDefault(); wizardStep===3?submitCampaign():setStep(wizardStep+1); return;}
  if(button.id==='wizardPrev'){event.preventDefault(); setStep(wizardStep-1); return;}
  if(button.dataset.action==='applyGoal'){event.preventDefault(); const goal=document.querySelector('#campaignModal .ai-suggestion p'); const target=document.querySelector('#campaignModal textarea'); if(target&&goal){target.dataset.aiGoal=goal.textContent; target.value=target.value+'\n'+goal.textContent;} toast('AI建议已写入活动目标'); return;}
  if(button.dataset.close){event.preventDefault(); closeLayer(button.dataset.close); return;}
});

/* Shared enterprise-console interactions: dynamic buttons and workflow records. */
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeLayer(b.dataset.close)));
$$('.modal-layer').forEach(layer=>layer.addEventListener('click',e=>{if(e.target===layer)closeLayer(layer.id)}));
const approvalData={act001:{no:'ACT-2026-0921',title:'上海—三亚国庆早鸟',type:'活动发布审批',owner:'李洋',budget:'32万元',audience:'36,420人',product:'三亚国庆早鸟包',channel:'App + 短信',current:2},pkg001:{no:'PKG-2026-0834',title:'国际中转安心包 V2',type:'产品包复核',owner:'王晨',budget:'—',audience:'—',product:'联程 + 住宿 + 城市游',channel:'官网 + OTA',current:1},content001:{no:'CNT-2026-1186',title:'国庆目的地种草内容',type:'内容合规审批',owner:'AIGC工坊',budget:'—',audience:'—',product:'三亚目的地内容',channel:'App + 微信',current:3}};
function renderApproval(id='act001'){const d=approvalData[id]||approvalData.act001;const detail=$('#approvalDetail');if(!detail)return;$('#approvalNo').textContent=d.no;detail.innerHTML=`<div class="approval-overview"><div><span>申请类型</span><b>${d.type}</b></div><div><span>申请人</span><b>${d.owner}</b></div><div><span>活动预算</span><b>${d.budget}</b></div><div><span>当前节点</span><b>${d.current===1?'产品确认':d.current===2?'营销负责人':'合规复核'}</b></div></div><div class="approval-timeline"><div class="approval-node done"><i>✓</i><b>创建</b><span>已完成</span></div><div class="approval-node ${d.current>1?'done':'current'}"><i>${d.current>1?'✓':'2'}</i><b>产品确认</b><span>${d.current>1?'已完成':'待处理'}</span></div><div class="approval-node ${d.current>2?'done':d.current===2?'current':''}"><i>${d.current>2?'✓':'3'}</i><b>营销审批</b><span>${d.current>2?'已完成':d.current===2?'待处理':'未开始'}</span></div><div class="approval-node ${d.current>=3?'current':''}"><i>4</i><b>合规复核</b><span>${d.current>=3?'待处理':'未开始'}</span></div><div class="approval-node"><i>5</i><b>发布</b><span>未开始</span></div></div><div class="approval-checks"><div class="approval-check"><i><i data-lucide="check"></i></i><span><b>客群与保护规则</b><small>${d.audience} · 已排除免打扰和营销疲劳客户</small></span></div><div class="approval-check"><i><i data-lucide="check"></i></i><span><b>产品资格校验</b><small>${d.product} · 价格、库存、权益可用</small></span></div><div class="approval-check"><i><i data-lucide="check"></i></i><span><b>渠道与频控</b><small>${d.channel} · 7天最多触达2次</small></span></div><div class="approval-check"><i><i data-lucide="alert-circle"></i></i><span><b>人工审批</b><small>需确认预算和活动目标一致性</small></span></div></div><div class="approval-actions"><button class="btn danger" data-approval-action="reject">退回修改</button><button class="btn primary" data-approval-action="approve">通过并进入下一节点</button></div>`;$$('[data-approval-action]',detail).forEach(b=>b.addEventListener('click',()=>{selectedDecision=b.dataset.approvalAction;$('#decisionSubtitle').textContent=d.title;$('#decisionComment').value=selectedDecision==='approve'?'产品、客群与渠道配置符合要求，同意进入合规复核。':'请补充预算依据、产品库存证明和内容事实来源后重新提交。';openLayer('decisionModal')}));icons()}
$$('.approval-item').forEach(item=>item.addEventListener('click',()=>{$$('.approval-item').forEach(x=>x.classList.remove('active'));item.classList.add('active');renderApproval(item.dataset.approval)}));renderApproval();
$$('.decision-choice').forEach(b=>b.addEventListener('click',()=>{$$('.decision-choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedDecision=b.dataset.decision;$('#decisionComment').value=selectedDecision==='approve'?'产品、客群与渠道配置符合要求，同意进入合规复核。':'请补充预算依据、产品库存证明和内容事实来源后重新提交。'}));
$('#confirmDecision')?.addEventListener('click',()=>{const title=$('#decisionSubtitle')?.textContent||'活动';closeLayer('decisionModal');toast(selectedDecision==='approve'?`审批通过：${title}已进入下一审批节点`:`已退回：${title}返回创建人修改`);const active=$('.approval-item.active');if(active){active.querySelector('em').textContent=selectedDecision==='approve'?'已通过':'已退回';active.querySelector('em').className=selectedDecision==='approve'?'pill':'pill red'} });
const roleData={operator:['营销运营','28','18','华东区域'],approver:['活动审批人','8','12','全国营销活动'],product:['产品管理员','12','15','产品管理平台同步范围'],analyst:['效果分析员','16','10','全量脱敏数据'],security:['安全管理员','4','22','安全与审计范围']};
$$('.role-item').forEach(item=>item.addEventListener('click',()=>{const d=roleData[item.dataset.role];$$('.role-item').forEach(x=>x.classList.remove('active'));item.classList.add('active');$('#roleTitle').textContent=d[0];$('#roleMembers').textContent=d[1];$('#roleFunctions').textContent=d[2];$('#roleScope').textContent=d[3];toast(`已切换角色：${d[0]}`)}));
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.classList.contains('icon-btn')&&!b.dataset.close)toast('通知中心：当前无未读告警');if(b.classList.contains('action')&&!b.dataset.action&&!b.dataset.openCampaign&&!b.dataset.openOpportunity&&!b.dataset.audience)toast(`已打开${b.textContent.trim()}详情`);if(b.classList.contains('toolbar-strip')||b.closest('.toolbar-strip')&&b.textContent.trim()==='查询')toast('查询完成：已刷新当前列表');if(b.textContent.trim()==='查看产品')toast('产品详情已打开：机票、行李和选座权益可用')});


